### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Subject-4** [EvolSoft/LimitHeight#1]
Does this allow u to remove the default height limit of MC:BE?

**Comment by Flavius12** [comment]
Can you be more clearer?

**Comment by Subject-4** [comment]
If I set the height limit to like 300, would I be able to build up to 300 or would the default message pop up when I reach 256 block height

**Comment by Flavius12** [comment]
The default message will be displayed only if you bypass the height limit specified in configuration
